---
- hosts: controller
  gather_facts: false
  tasks:
    
    - name: connect to database
      mysql_db:
        login_host: localhost
        login_user: root
        login_password: root
        name: keystone
        state: present
    - name: localhost keystone user
      mysql_user:
        login_host: localhost
        login_user: root
        login_password: root
        name: keystone
        password: keystone
        priv: keystone.*:ALL 
        host: "{{ item }}"
        state: present
      with_items:
        - localhost
        - '%'

    - name: token
      shell: openssl rand -hex 10 > /root/token
      tags: a

    - name: keystone service
      shell: echo "manual" > /etc/init/keystone.override
      tags: b

    - name: install keystone package
      apt: name={{item}} state=latest
      with_items: 
        - keystone
        - apache2
        - libapache2-mod-wsgi
      tags: c

    - name: keystone defaults
      ini_file: dest=/etc/keystone/keystone.conf
                section=DEFAULT
                option=admin_token
                value=06686bc612766e0325c2
                backup=yes
      tags: d


    - name: keystone database
      ini_file: dest=/etc/keystone/keystone.conf
                section=database
                option=connection
                value=mysql://keystone:keystone@controller/keystone
                backup=yes
      tags: e

    - name: token
      ini_file: dest=/etc/keystone/keystone.conf
                section=token
                option=provider
                value=fernet
                backup=yes 
      tags: f

    - name: create database tables
      shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
      tags: g

    - name: initialize fernet keys
      command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
      tags: h

    - name: apache2.conf
      lineinfile: dest=/etc/apache2/apache2.conf
                  line='ServerName controller'                
      tags: i

    - name: create file
      copy: src=/etc/ansible/yml/wsgi-keystone.conf.j2 dest=/etc/apache2/sites-available/wsgi-keystone.conf
      tags: j

    - name: enable identity service virtual hosts
      shell: ln -s /etc/apache2/sites-available/wsgi-keystone.conf /etc/apache2/sites-enabled
      tags: k

    - name: apache2 restart
      service: name=apache2 state=restarted
      tags: l

    - name: remove SQL lite database
      shell: rm -f /var/lib/keystone/keystone.db
      tags: m

    - name: copy export.sh 
      copy: src=/etc/ansible/yml/export.sh
            dest=/root/export.sh 
      tags: n

    - name: copy admin.sh
      copy: src=/etc/ansible/yml/admin.sh
            dest=/root/admin.sh
      tags: o

    - name: script
      command: bash export.sh 
      tags: p

    - name: admin user
      command: bash admin.sh
      tags: q
