---
- hosts: one
  tasks: 
    - name: install package
      apt: name=software-properties-common state=present
     
    - name: add repository
      apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/mitaka main' filename=cloudarchive-mitaka.list state=present
    
    - name: update
      apt: 
        update_cache=yes
      tags: dinesh
     
    - name: upgrade
      apt:
        upgrade=dist
        force=yes
      tags: sekhar

    - name: install package
      apt: name=python-openstackclient state=present force=yes
      tags: narsi
